# Generated by Django 3.2.23 on 2024-02-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=2000)),
                ('publish_date', models.DateTimeField()),
                ('author', models.CharField(max_length=80)),
                ('publisher', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=2000)),
                ('video_url', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(),
        ),
    ]
