# Generated by Django 3.2.23 on 2024-02-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240208_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('population_2023', models.IntegerField()),
                ('population_2022', models.IntegerField()),
                ('population_2020', models.IntegerField()),
                ('population_2015', models.IntegerField()),
                ('population_2000', models.IntegerField()),
            ],
        ),
    ]
