# Generated by Django 3.2.23 on 2024-03-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_population'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='member_id',
            new_name='author',
        ),
    ]
