# Generated by Django 5.0.3 on 2024-04-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
    ]
