# Generated by Django 5.0.3 on 2024-04-14 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_comment_name_alter_comment_posts_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                default=0, related_name="comment_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
