# Generated by Django 5.0.3 on 2024-04-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0022_alter_comment_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="categroy", max_length=255),
        ),
    ]
