# Generated by Django 5.0.3 on 2024-04-18 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0024_category_slug_alter_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
